name: Build macOS App

on:
  push:
    branches:
      - main  # Run when pushing to the main branch
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your project’s Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed --name "ArduinoReader" --icon=app.icns arduino_reader_final.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/ArduinoReader.app
